id: DCC5466F3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-25T01:08:59+00:00'
last_modified: '2022-05-26T10:27:35.290438+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    72dc:
      image_group_id: I1PD95863
      title: བྱང་ཆུབ་སེམས་ཀྱི་འགྲེལ་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1634
      order: 18
      base_file: 72dc.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
